### ISSUE TITLE
Install instructions would be good(!)

### ISSUE THREAD

**Issue by pperrin** [bueltge/Drafts-Feed#1]
Hi

Seems just what I need - but off the shelf wordpress install wants a zip... off to find out what that needs to look like(!) Would be good to have instructions in the read.me

**Comment by pperrin** [comment]
Hi - ok downloaded the zip from here, uploaded it to wp using the standard plugin install .zip page - worked fine. Guess the screen shots aren't really needed - but it works ;)

**Comment by bueltge** [comment]
Yes, the screenshots are only for the readme to read it on github.
But github include all files inside the download, no customization possible.
Best
